# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2437788e3916d62dfaa5686a23918d9481247d6bbb96e5e4cc4a1a409c4500d5a12b0d4695546c5ed2bc9c3951d5ba2f72d38996dcd881f29f8e7ad46be18987

test:
  secret_key_base: 79ad67867b4f686c059f85e6eabf4e1887ff50985724175e1149b8e7567a172e6335ec17e07f5140319375381eefdda16e6e427e1106dd0d6a904dc16857d91a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
